baseURL = 'https://www.darius-weber.de/'
languageCode = 'en-us'
title = 'Darius Weber'
theme = 'hugo-profile'

[outputs]
home = ["HTML"]
page = ["HTML", "RSS"]

[[Menus.main]]
identifier = "terms"
name = "Terms & Privacy Policy"
title = "Terms & Privacy Policy"
url = "/terms"
weight = 10

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blog"
weight = -10

[[Menus.main]]
identifier = "projects"
name = "Projects"
title = "Projects"
url = "/projects"
weight = -20

[params]
title = "Darius Weber"
copyright = "Darius Weber"
favicon = "/favicon.png"
siteRepository = "https://github.com/ManticSic/www.darius-weber.de"
rev = "1234567"
mathjax = false
animate = true

[[params.socialLinks]]
icon = "fab fa-xing"
url = "https://www.xing.com/profile/Darius_Weber3"

[[params.socialLinks]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/darius-weber-49bb24215/"

[[params.socialLinks]]
icon = "fab fa-github"
url = "https://github.com/ManticSic"

[[params.socialLinks]]
icon = "fab fa-stack-overflow"
url = "https://stackoverflow.com/users/5663348/d-weber"

[params.navbar]
disableSearch = true
brandLogo = "/logo.png"

[params.hero]
enable = true
intro = "Hi, my name is"
title = "Darius"
subtitle = "my goal: enable developers"
content = """
I aim to be of service to my colleagues, removing unnecessary obstacles and fostering a vision for a common goals.  
On top of that, as a DevSecOps Engineer, I strive to make security and compliance engaging rather than tedious and frustrating.
"""
image = "/images/me.jpg"
roundImage = true

[params.hero.button]
enable = true
name = "Learn more"
url = "/#experience"
newPage = false

[params.experience]
enable = true

[[params.experience.items]]
company = "SCHUMANN"
companyUrl = "https://prof-schumann.com/"
job = "Product Owner"
date = "Since March 2024"
content = """
Eager to lead and inspire, I've actively pursued training programs in leadership and management, aiming to harness my skills for broader impact.

In mid-2023, following a reorganization, I assumed some of our team leader's responsibilities on a temporary basis.
Recognizing the potential to enhance the quality and value of our work, by the end of 2023, I advocated for assuming these tasks permanently.

Since March 2024, I have officially overseen the entire development infrastructure, among other responsibilities.
"""

[[params.experience.items]]
company = "SCHUMANN"
companyUrl = "https://prof-schumann.com/"
job = "DevSecOps Engineer"
date = "Sep 2021 - Feb 2024"
content = """
When I first joined the company, I knew there were significant transformations underway.
We were embarking on development for Linux and transitioning from SVN to Git - areas where I held considerable expertise.
I became an integral part of the centralized DevOps team tasked with spearheading these changes.

As a passionate advocate for DevSecOps principles,
I derive immense satisfaction from sharing knowledge and fostering collaboration

Alongside my primary responsibilities, I was promptly invited to contribute to a committee dedicated to enhancing the developer experience.
Today, I proudly represent this group, and together, we've spearheaded several impactful initiatives.  
Notably, we've implemented regular developer satisfaction surveys, with a technology-focused approach, to ensure continuous improvement.
Furthermore, we've established a committee tasked with enhancing software supply chain security and eliminating obstacles hindering progress.
"""

[[params.experience.items]]
company = "dff solutions"
companyUrl = "https://www.circlon.de/"
job = "Software Developer"
date = "Sep 2014 - Sep 2021"
content = """
I came here through a former colleague to set up a new team to develop an existing delivery tracking system for food retail.

Our main tasks were to modernize .Net servers and to stabilise an Android app written with Angular.
In addition to regular development I was responsible for improving the development process by increasing the automation of the build process.

Together we have managed to turn one of the worst running projects into a flagship project with just a few people in less than one year.

Shortly before the company folded, we developed a service to track, combine, and analyse truck telematics from multiple vendors.
"""

[[params.experience.items]]
company = "xplace GmbH"
companyUrl = "https://www.xplace-group.com/"
job = "Software Developer"
date = "Oct 2014 - Aug 2020"
content = """
I started as an intern in the design department and later worked as media design assistant.
After one year I started an apprenticeship as software developer.

My focus was on developing applications for the POS in Java, TypeScript, .Net, and Python. Later I was responsible for release and package management.
In addition to my development tasks, I took over the technical project management for a large customer.

My highlight at xplace was the introduction of Git and GitLab where I gave some internal trainings.
"""

[params.education]
enable = true
index = false

[[params.education.items]]
title = "Certified DevSecOps Engineer"
date = "On going"
content = ""

[params.education.items.school]
name = "EC Council"
url = "https://www.eccouncil.org/"

[[params.education.items]]
title = "Management and Leadship Training"
date = "Oct 2023 - March 2024"
content = "Content: leadership approaches and theories; role and tasks of a manager; change from colleague to superior; perception and communication; motivation; dealing with conflicts; formulating goals; delegating"

[params.education.items.school]
name = "Weinreich recruit & develop"
url = "https://www.weinreich-rd.de/"

[[params.education.items]]
title = "Computer Science Expert"
date = "Aug. 2015 - Jan 2018"
GPA = "86 Points (Good)"
content = """
Subject area: Software Development
"""

[params.education.items.school]
name = "Göttingen BBS 2"
url = "https://www.bbs2goe.de/"

[[params.education.items]]
title = "Abitur / High School"
date = "Jun 2013"
GPA = "500 out of 900 Points (2.8)"
content = """
Main focus: science (Maths, Physics, Chemistry)

I wrote my specialisted work about "Ariosophy - The Root of National Socialism" and passed with 8 out of 15 points.
"""

[params.education.items.school]
name = "KGS Moringen"
url = "https://kgsmoringen.de/"

[params.contact]
enable = true
content = "My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! "
email = "darius.weber@posteo.de"
btnName = "Mail me"
